import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

export default function AITools() {
  useEffect(() => {
    // Trigger dynamic interactions on mount
  }, []);

  return (
    <main style={{ paddingTop: '80px' }}>
{/*  ═══ HERO ═══  */}
  <section className="ai-hero" id="hero">
    <div className="container">
      <div className="ai-hero-grid">
        <div>
          <div className="ai-hero-badge"><i className="fas fa-brain"></i> AI-Powered Platform</div>
          <h1 className="ai-hero-title">
            <span className="gradient-text-orange">Intelligent AI</span> Tools<br/>
            Built for <span className="gradient-text-blue">Modern Business</span>
          </h1>
          <p className="ai-hero-desc">9 production-ready AI solutions that automate your operations, generate revenue, and deliver measurable results — deployed in days, not months.</p>
          <div style={{"display": "flex", "gap": "14px", "flexWrap": "wrap", "marginBottom": "36px"}}>
            <Link  to="#tools" className="cta-btn primary"><i className="fas fa-robot"></i> Explore All Tools</Link>
            <Link  to="#demo" className="cta-btn secondary"><i className="fas fa-play-circle"></i> Live Demo</Link>
            <Link  to="#pricing" className="cta-btn secondary">View Pricing</Link>
          </div>
          <div className="ai-hero-stats">
            <div className="ai-hero-stat"><strong className="stat-number-value" data-target="9" data-suffix="">0</strong><span>AI Solutions</span></div>
            <div className="ai-hero-stat"><strong className="stat-number-value" data-target="100" data-suffix="+">0</strong><span>Deployments</span></div>
            <div className="ai-hero-stat"><strong className="stat-number-value" data-target="4.9" data-suffix="/5">0</strong><span>Avg Rating</span></div>
            <div className="ai-hero-stat"><strong className="stat-number-value" data-target="14" data-suffix=" days">0</strong><span>Free Pilot</span></div>
          </div>
        </div>
        <div>
          <div className="ai-hero-demo-card">
            <div className="demo-card-header">
              <div className="demo-status-dot"></div>
              <span style={{"fontWeight": "700", "fontSize": ".92rem"}}>AI Customer Support Agent</span>
              <span style={{"marginLeft": "auto", "fontSize": ".75rem", "color": "#94A3B8"}}>Live Demo</span>
            </div>
            <div className="demo-chat" id="hero-chat">
              <div className="chat-bubble ai">👋 Hello! I'm your AI support agent. Ask me about orders, returns, payments, or any product questions.</div>
            </div>
            <div className="demo-input-row" style={{"marginBottom": "12px"}}>
              <input className="demo-input" id="hero-input" type="text" placeholder="Ask me anything about your order..." autoComplete="off" />
              <button className="demo-send-btn" id="hero-send-btn" onclick="heroSend()"><i className="fas fa-paper-plane"></i></button>
            </div>
            <div style={{"display": "flex", "gap": "8px", "flexWrap": "wrap"}}>
              <button className="quick-btn" onclick="heroQuick('Track my order #12345')">📦 Track order</button>
              <button className="quick-btn" onclick="heroQuick('How do I return an item?')">↩️ Returns</button>
              <button className="quick-btn" onclick="heroQuick('What payment methods do you accept?')">💳 Payments</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {/*  ═══ 9 AI TOOLS GRID ═══  */}
  <section style={{"padding": "100px 0", "background": "#020617"}} id="tools">
    <div className="container">
      <div className="section-head-center">
        <div className="section-eyebrow eyebrow-orange"><i className="fas fa-th-large"></i> All 9 Solutions</div>
        <h2 className="section-title">AI Tools for <span className="gradient-text-cyan">Every Business Need</span></h2>
        <p className="section-subtitle">From customer support to predictive analytics — each tool is custom-built, integrated with your stack, and deployed with full monitoring.</p>
      </div>
      <div className="tools-grid gsap-stagger">
        <div className="tool-card tool-cyan"><div className="tool-icon-wrap"><i className="fas fa-comment-dots"></i></div><h3>AI Customer Support Agent</h3><p>24/7 intelligent chatbot trained on your business knowledge. Resolves 80% of queries without human intervention with smart escalation.</p><div className="tool-tags"><span className="tool-tag">GPT-4o</span><span className="tool-tag">LangChain</span><span className="tool-tag">RAG</span><span className="tool-tag">WebSocket</span></div><div className="tool-metrics"><div className="tool-metric"><strong className="gradient-text-cyan">80%</strong><span>Resolution</span></div><div className="tool-metric"><strong className="gradient-text-cyan">24/7</strong><span>Available</span></div><div className="tool-metric"><strong className="gradient-text-cyan">-65%</strong><span>Costs</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('chatbot')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-blue"><div className="tool-icon-wrap"><i className="fas fa-file-alt"></i></div><h3>Intelligent Document Processing</h3><p>Extract, classify, and process invoices, contracts, and forms at scale with 99.2% accuracy. Auto-populate your ERP and databases.</p><div className="tool-tags"><span className="tool-tag">OCR</span><span className="tool-tag">GPT-4 Vision</span><span className="tool-tag">FastAPI</span><span className="tool-tag">Python</span></div><div className="tool-metrics"><div className="tool-metric"><strong className="gradient-text-blue">99.2%</strong><span>Accuracy</span></div><div className="tool-metric"><strong className="gradient-text-blue">500ms</strong><span>Per Doc</span></div><div className="tool-metric"><strong className="gradient-text-blue">-90%</strong><span>Manual Work</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('document')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-orange"><div className="tool-icon-wrap"><i className="fas fa-funnel-dollar"></i></div><h3>AI Sales & Lead Generation</h3><p>Automated prospect research, lead scoring, and personalized outreach sequences. CRM-integrated. Book meetings while you sleep.</p><div className="tool-tags"><span className="tool-tag">n8n</span><span className="tool-tag">OpenAI</span><span className="tool-tag">HubSpot</span><span className="tool-tag">Apollo</span></div><div className="tool-metrics"><div className="tool-metric"><strong className="gradient-text-orange">3x</strong><span>More Leads</span></div><div className="tool-metric"><strong className="gradient-text-orange">+40%</strong><span>Conv. Rate</span></div><div className="tool-metric"><strong className="gradient-text-orange">85%</strong><span>Time Saved</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('sales')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-green"><div className="tool-icon-wrap"><i className="fas fa-chart-line"></i></div><h3>Predictive Analytics AI</h3><p>Forecast revenue, detect churn before it happens, and identify growth opportunities. Natural language querying — no SQL needed.</p><div className="tool-tags"><span className="tool-tag">Python</span><span className="tool-tag">Prophet</span><span className="tool-tag">Plotly</span><span className="tool-tag">Gemini</span></div><div className="tool-metrics"><div className="tool-metric"><strong style={{"color": "#10B981"}}>94%</strong><span>Accuracy</span></div><div className="tool-metric"><strong style={{"color": "#10B981"}}>30 days</strong><span>Look-ahead</span></div><div className="tool-metric"><strong style={{"color": "#10B981"}}>Real-time</strong><span>Dashboards</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('analytics')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-purple"><div className="tool-icon-wrap"><i className="fas fa-pen-nib"></i></div><h3>AI Content Generation Engine</h3><p>SEO blogs, product descriptions, social media, email campaigns in your brand voice. Multi-language. Direct CMS publishing.</p><div className="tool-tags"><span className="tool-tag">GPT-4</span><span className="tool-tag">Claude</span><span className="tool-tag">WordPress</span><span className="tool-tag">Webflow</span></div><div className="tool-metrics"><div className="tool-metric"><strong style={{"color": "#A78BFA"}}>50+</strong><span>Content Types</span></div><div className="tool-metric"><strong style={{"color": "#A78BFA"}}>12</strong><span>Languages</span></div><div className="tool-metric"><strong style={{"color": "#A78BFA"}}>-80%</strong><span>Writing Time</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('content')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-pink"><div className="tool-icon-wrap"><i className="fas fa-microphone-alt"></i></div><h3>AI Voice & Phone Agent</h3><p>Inbound/outbound AI calls that sound human. Handles appointments, surveys, follow-ups. Integrates with Twilio and VAPI.</p><div className="tool-tags"><span className="tool-tag">Twilio</span><span className="tool-tag">VAPI</span><span className="tool-tag">Whisper</span><span className="tool-tag">ElevenLabs</span></div><div className="tool-metrics"><div className="tool-metric"><strong style={{"color": "#F472B6"}}>98%</strong><span>Human-like</span></div><div className="tool-metric"><strong style={{"color": "#F472B6"}}>200ms</strong><span>Response</span></div><div className="tool-metric"><strong style={{"color": "#F472B6"}}>-70%</strong><span>Call Cost</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('rag')">Learn More <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-blue"><div className="tool-icon-wrap"><i className="fas fa-database"></i></div><h3>RAG Knowledge Base AI</h3><p>Train AI on your entire company knowledge. Employees get instant, accurate answers with source citations. Zero hallucinations.</p><div className="tool-tags"><span className="tool-tag">Pinecone</span><span className="tool-tag">Qdrant</span><span className="tool-tag">LangChain</span><span className="tool-tag">OpenAI</span></div><div className="tool-metrics"><div className="tool-metric"><strong className="gradient-text-blue">10M+</strong><span>Doc Tokens</span></div><div className="tool-metric"><strong className="gradient-text-blue">&lt; 1s</strong><span>Response</span></div><div className="tool-metric"><strong className="gradient-text-blue">Zero</strong><span>Hallucinations</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('rag')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-green"><div className="tool-icon-wrap"><i className="fas fa-boxes"></i></div><h3>Inventory Optimization AI</h3><p>Predict stock requirements, auto-reorder at optimal levels, and prevent overstock/stockout. ML trained on your sales history.</p><div className="tool-tags"><span className="tool-tag">Prophet</span><span className="tool-tag">Supabase</span><span className="tool-tag">n8n</span><span className="tool-tag">Shopify</span></div><div className="tool-metrics"><div className="tool-metric"><strong style={{"color": "#10B981"}}>-35%</strong><span>Hold Costs</span></div><div className="tool-metric"><strong style={{"color": "#10B981"}}>-92%</strong><span>Stockouts</span></div><div className="tool-metric"><strong style={{"color": "#10B981"}}>+28%</strong><span>Profit</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('analytics')">Learn More <i className="fas fa-arrow-right"></i></button></div>
        <div className="tool-card tool-orange"><div className="tool-icon-wrap"><i className="fas fa-envelope-open-text"></i></div><h3>AI Email Marketing Engine</h3><p>Hyper-personalized campaigns with send-time optimization, subject line testing, and behavioral trigger flows — fully automated.</p><div className="tool-tags"><span className="tool-tag">GPT-4</span><span className="tool-tag">Mailchimp</span><span className="tool-tag">SendGrid</span><span className="tool-tag">n8n</span></div><div className="tool-metrics"><div className="tool-metric"><strong className="gradient-text-orange">+62%</strong><span>Open Rate</span></div><div className="tool-metric"><strong className="gradient-text-orange">+38%</strong><span>Click Rate</span></div><div className="tool-metric"><strong className="gradient-text-orange">5x ROI</strong><span>Average</span></div></div><button className="tool-demo-btn" onclick="openDemoTool('content')">Live Demo <i className="fas fa-arrow-right"></i></button></div>
      </div>
    </div>
  </section>

  {/*  ═══ INTERACTIVE DEMO SECTION ═══  */}
  <section className="demo-section" id="demo">
    <div className="container">
      <div className="section-head-center" style={{"marginBottom": "40px"}}>
        <div className="section-eyebrow eyebrow-cyan"><i className="fas fa-play-circle"></i> Interactive Demos</div>
        <h2 className="section-title">Try Our AI Tools <span className="gradient-text-cyan">Right Now</span></h2>
        <p className="section-subtitle">Select a tool and interact with live AI. No signup required — experience the intelligence first-hand.</p>
      </div>
      <div className="demo-tabs" id="demo-tabs">
        <button className="demo-tab active" data-demo="chatbot">💬 AI Chatbot</button>
        <button className="demo-tab" data-demo="document">📄 Document AI</button>
        <button className="demo-tab" data-demo="sales">🎯 Sales AI</button>
        <button className="demo-tab" data-demo="analytics">📊 Analytics AI</button>
        <button className="demo-tab" data-demo="content">✍️ Content AI</button>
        <button className="demo-tab" data-demo="rag">🧠 RAG KB</button>
      </div>
      {/*  Chatbot  */}
      <div className="demo-panel active" id="demo-chatbot"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>AI Customer Support · Online</span></div><div className="demo-interface-body"><div id="demo-chat-messages" style={{"display": "flex", "flexDirection": "column", "gap": "10px", "maxHeight": "220px", "overflowY": "auto", "marginBottom": "16px"}}><div className="chat-bubble ai">Hello! I can help with order tracking, returns, product questions, and account issues. What do you need?</div></div><div className="demo-input-row"><input className="demo-input" id="demo-chat-input" type="text" placeholder="Type your question..." autoComplete="off" /><button className="demo-send-btn" onclick="demoSend('chatbot')"><i className="fas fa-paper-plane"></i></button></div><div style={{"display": "flex", "gap": "8px", "marginTop": "10px", "flexWrap": "wrap"}}><button className="quick-btn" onclick="quickAsk('chatbot','Track my order #12345')">📦 Track order</button><button className="quick-btn" onclick="quickAsk('chatbot','How do I return an item?')">↩️ Returns</button><button className="quick-btn" onclick="quickAsk('chatbot','What payment methods do you accept?')">💳 Payments</button></div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-cyan" style={{"marginBottom": "12px"}}><i className="fas fa-comment-dots"></i> AI Customer Support</div><h3>Resolve 80% of queries automatically</h3><ul><li><i className="fas fa-check-circle"></i> Trained on your product catalog, FAQs, and policies</li><li><i className="fas fa-check-circle"></i> Real-time order tracking via API integration</li><li><i className="fas fa-check-circle"></i> Intelligent escalation with full conversation context</li><li><i className="fas fa-check-circle"></i> Multi-language support across 12+ languages</li><li><i className="fas fa-check-circle"></i> WhatsApp, web widget, and Telegram deployments</li><li><i className="fas fa-check-circle"></i> Sentiment analysis and satisfaction scoring</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>80%</strong><span>Auto-resolution</span></div><div className="demo-kpi"><strong>&lt;2s</strong><span>Response</span></div><div className="demo-kpi"><strong>4.8★</strong><span>CSAT Score</span></div></div></div></div></div>
      {/*  Document  */}
      <div className="demo-panel" id="demo-document"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>Document Processing AI · Ready</span></div><div className="demo-interface-body"><div style={{"border": "2px dashed rgba(37,99,235,.3)", "borderRadius": "12px", "padding": "24px", "textAlign": "center", "marginBottom": "16px", "cursor": "pointer"}} onclick="simulateDocProcess()"><i className="fas fa-cloud-upload-alt" style={{"fontSize": "2rem", "color": "rgba(37,99,235,.5)", "display": "block", "marginBottom": "10px"}}></i><div style={{"fontSize": ".88rem", "color": "#94A3B8"}}>Drop invoice / contract / form here<br/><span style={{"color": "#2563EB", "cursor": "pointer"}}>or click to simulate processing</span></div></div><div id="doc-output" style={{"display": "none", "background": "rgba(15,23,42,.8)", "border": "1px solid rgba(255,255,255,.08)", "borderRadius": "10px", "padding": "16px"}}><div style={{"fontSize": ".72rem", "color": "#06B6D4", "fontWeight": "700", "letterSpacing": "1px", "marginBottom": "10px"}}>EXTRACTED DATA</div><div id="doc-json" style={{"fontFamily": "monospace", "fontSize": ".78rem", "color": "#93C5FD", "whiteSpace": "pre-line", "lineHeight": "1.8"}}></div></div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-blue" style={{"marginBottom": "12px"}}><i className="fas fa-file-alt"></i> Document AI</div><h3>Process 10,000+ documents per day</h3><ul><li><i className="fas fa-check-circle"></i> Invoices, contracts, forms, passports, and reports</li><li><i className="fas fa-check-circle"></i> GPT-4 Vision + custom OCR for handwritten text</li><li><i className="fas fa-check-circle"></i> Auto-populate ERP, CRM, and database systems</li><li><i className="fas fa-check-circle"></i> Validation rules with exception flagging</li><li><i className="fas fa-check-circle"></i> PDF, DOCX, JPG, PNG, TIFF file support</li><li><i className="fas fa-check-circle"></i> Full audit trail with human review workflow</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>99.2%</strong><span>Accuracy</span></div><div className="demo-kpi"><strong>500ms</strong><span>Per Doc</span></div><div className="demo-kpi"><strong>-90%</strong><span>Manual Entry</span></div></div></div></div></div>
      {/*  Sales  */}
      <div className="demo-panel" id="demo-sales"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>Sales AI · Prospecting Engine</span></div><div className="demo-interface-body" style={{"padding": "20px"}}><div style={{"fontSize": ".8rem", "color": "#94A3B8", "marginBottom": "12px"}}>Enter a company or industry to find qualified leads:</div><div className="demo-input-row" style={{"marginBottom": "16px"}}><input className="demo-input" id="sales-input" type="text" placeholder="e.g. SaaS companies in healthcare, 50-500 employees..." /><button className="demo-send-btn" onclick="simulateSales()"><i className="fas fa-search"></i></button></div><div id="sales-output" style={{"display": "flex", "flexDirection": "column", "gap": "10px", "maxHeight": "220px", "overflowY": "auto"}}></div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-orange" style={{"marginBottom": "12px"}}><i className="fas fa-funnel-dollar"></i> Sales AI</div><h3>Fill your pipeline automatically</h3><ul><li><i className="fas fa-check-circle"></i> AI prospect research using LinkedIn, Apollo, and web data</li><li><i className="fas fa-check-circle"></i> Automated lead scoring with 50+ data signals</li><li><i className="fas fa-check-circle"></i> Hyper-personalized outreach email sequences</li><li><i className="fas fa-check-circle"></i> CRM sync with HubSpot, Salesforce, Pipedrive</li><li><i className="fas fa-check-circle"></i> Meeting booking with calendar integration</li><li><i className="fas fa-check-circle"></i> A/B testing with AI-optimized subject lines</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>3x</strong><span>More Leads</span></div><div className="demo-kpi"><strong>+40%</strong><span>Conv. Rate</span></div><div className="demo-kpi"><strong>85%</strong><span>Time Saved</span></div></div></div></div></div>
      {/*  Analytics  */}
      <div className="demo-panel" id="demo-analytics"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>Analytics AI · Natural Language Query</span></div><div className="demo-interface-body"><div id="analytics-chat" style={{"display": "flex", "flexDirection": "column", "gap": "10px", "maxHeight": "200px", "overflowY": "auto", "marginBottom": "16px"}}><div className="chat-bubble ai">📊 Ask me anything about your business data. I can analyze trends, predict outcomes, and generate reports.</div></div><div className="demo-input-row"><input className="demo-input" id="analytics-input" type="text" placeholder="e.g. What will our revenue be next month?" autoComplete="off" /><button className="demo-send-btn" onclick="demoSend('analytics')"><i className="fas fa-paper-plane"></i></button></div><div style={{"display": "flex", "gap": "8px", "marginTop": "10px", "flexWrap": "wrap"}}><button className="quick-btn" onclick="quickAsk('analytics','Predict revenue for next quarter')">📈 Revenue forecast</button><button className="quick-btn" onclick="quickAsk('analytics','Which customers are at churn risk?')">⚠️ Churn risk</button><button className="quick-btn" onclick="quickAsk('analytics','Show top performing products this week')">🏆 Top products</button></div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-green" style={{"marginBottom": "12px"}}><i className="fas fa-chart-line"></i> Predictive Analytics AI</div><h3>Ask questions, get business intelligence</h3><ul><li><i className="fas fa-check-circle"></i> Natural language interface — no SQL or data skills needed</li><li><i className="fas fa-check-circle"></i> 30-day revenue and demand forecasting (94% accuracy)</li><li><i className="fas fa-check-circle"></i> Churn prediction with 3-week advance warning</li><li><i className="fas fa-check-circle"></i> Anomaly detection and automatic alerts</li><li><i className="fas fa-check-circle"></i> Connects to your existing BI tools and databases</li><li><i className="fas fa-check-circle"></i> Auto-generated reports in PDF and PowerPoint</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>94%</strong><span>Forecast Acc.</span></div><div className="demo-kpi"><strong>Real-time</strong><span>Data</span></div><div className="demo-kpi"><strong>-70%</strong><span>Report Time</span></div></div></div></div></div>
      {/*  Content  */}
      <div className="demo-panel" id="demo-content"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>Content AI · Generator</span></div><div className="demo-interface-body"><div style={{"marginBottom": "12px"}}><div style={{"fontSize": ".78rem", "color": "#94A3B8", "marginBottom": "8px"}}>Content type:</div><div style={{"display": "flex", "gap": "8px", "flexWrap": "wrap"}}><button className="content-type-btn active" onclick="setContentType(this,'blog')">Blog Post</button><button className="content-type-btn" onclick="setContentType(this,'social')">Social Media</button><button className="content-type-btn" onclick="setContentType(this,'email')">Email</button><button className="content-type-btn" onclick="setContentType(this,'product')">Product Desc</button></div></div><div className="demo-input-row" style={{"marginBottom": "12px"}}><input className="demo-input" id="content-input" type="text" placeholder="Enter your topic or keywords..." /><button className="demo-send-btn" onclick="generateContent()"><i className="fas fa-magic"></i></button></div><div id="content-output" style={{"background": "rgba(15,23,42,.5)", "border": "1px solid rgba(255,255,255,.08)", "borderRadius": "10px", "padding": "14px", "minHeight": "120px", "fontSize": ".85rem", "lineHeight": "1.7", "color": "#94A3B8", "whiteSpace": "pre-line"}}>Generated content will appear here... Click ✨ to generate.</div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-blue" style={{"marginBottom": "12px"}}><i className="fas fa-pen-nib"></i> Content Generation AI</div><h3>Create content 10x faster</h3><ul><li><i className="fas fa-check-circle"></i> SEO-optimized blog posts with meta descriptions</li><li><i className="fas fa-check-circle"></i> Platform-specific social media captions</li><li><i className="fas fa-check-circle"></i> Personalized email campaign sequences</li><li><i className="fas fa-check-circle"></i> Product descriptions in your brand voice</li><li><i className="fas fa-check-circle"></i> Direct publish to WordPress, Webflow, Shopify</li><li><i className="fas fa-check-circle"></i> 12-language translation with cultural adaptation</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>-80%</strong><span>Writing Time</span></div><div className="demo-kpi"><strong>50+</strong><span>Content Types</span></div><div className="demo-kpi"><strong>12</strong><span>Languages</span></div></div></div></div></div>
      {/*  RAG  */}
      <div className="demo-panel" id="demo-rag"><div className="demo-panels-grid"><div><div className="demo-interface"><div className="demo-interface-header"><div className="demo-dot red"></div><div className="demo-dot yellow"></div><div className="demo-dot green"></div><span style={{"marginLeft": "8px", "fontSize": ".8rem", "color": "#94A3B8"}}>RAG Knowledge Base · Apitide Docs</span></div><div className="demo-interface-body"><div id="rag-chat" style={{"display": "flex", "flexDirection": "column", "gap": "10px", "maxHeight": "200px", "overflowY": "auto", "marginBottom": "16px"}}><div className="chat-bubble ai">🧠 I'm trained on Apitide's full knowledge base. Ask me anything about our services, processes, or capabilities.</div></div><div className="demo-input-row"><input className="demo-input" id="rag-input" type="text" placeholder="Ask about our services, process, or pricing..." autoComplete="off" /><button className="demo-send-btn" onclick="demoSend('rag')"><i className="fas fa-paper-plane"></i></button></div><div style={{"display": "flex", "gap": "8px", "marginTop": "10px", "flexWrap": "wrap"}}><button className="quick-btn" onclick="quickAsk('rag','How long does a typical project take?')">⏱️ Timeline</button><button className="quick-btn" onclick="quickAsk('rag','What technologies do you specialize in?')">⚙️ Tech stack</button><button className="quick-btn" onclick="quickAsk('rag','Do you offer post-launch support?')">🛠️ Support</button></div></div></div></div><div className="demo-info-card"><div className="section-eyebrow eyebrow-cyan" style={{"marginBottom": "12px"}}><i className="fas fa-database"></i> RAG Knowledge Base AI</div><h3>Your company's AI brain</h3><ul><li><i className="fas fa-check-circle"></i> Ingest any document format: PDF, DOCX, Excel, web pages</li><li><i className="fas fa-check-circle"></i> Vector search with Pinecone or Qdrant for precision</li><li><i className="fas fa-check-circle"></i> Source citations in every response — zero hallucinations</li><li><i className="fas fa-check-circle"></i> Role-based access control and data permissions</li><li><i className="fas fa-check-circle"></i> Slack, Teams, and web widget integrations</li><li><i className="fas fa-check-circle"></i> Continuous learning as you add new documents</li></ul><div className="demo-kpi-row"><div className="demo-kpi"><strong>10M+</strong><span>Tokens</span></div><div className="demo-kpi"><strong>&lt;1s</strong><span>Response</span></div><div className="demo-kpi"><strong>Zero</strong><span>Hallucinations</span></div></div></div></div></div>
    </div>
  </section>

  {/*  ═══ WORKFLOW ═══  */}
  <section className="workflow-section" id="workflow">
    <div className="container">
      <div style={{"display": "grid", "gridTemplateColumns": "1fr 1fr", "gap": "80px", "alignItems": "start"}} className="workflow-grid-inner">
        <div>
          <div className="section-eyebrow eyebrow-orange"><i className="fas fa-project-diagram"></i> Workflow Examples</div>
          <h2 className="section-title">How Our AI<br/><span className="gradient-text-orange">Workflows Operate</span></h2>
          <p style={{"color": "#94A3B8", "marginBottom": "40px", "lineHeight": "1.7"}}>Every AI solution is built on a structured, auditable workflow. From data ingestion to final output — fully automated, monitored, and logged.</p>
          <div className="workflow-steps">
            <div className="workflow-step"><div className="step-num">01</div><div className="step-body"><h4>Data Ingestion & Normalization</h4><p>Connect to your databases, APIs, CRMs, and file systems. Data is cleaned, normalized, and validated before processing begins.</p></div></div>
            <div className="workflow-step"><div className="step-num">02</div><div className="step-body"><h4>AI Processing & Enrichment</h4><p>LLMs and custom ML models process the data — classifying, generating, predicting, or extracting based on your specific use case.</p></div></div>
            <div className="workflow-step"><div className="step-num">03</div><div className="step-body"><h4>Decision Engine & Business Rules</h4><p>Rules layer ensures all AI outputs meet your compliance requirements and business logic before any action is taken.</p></div></div>
            <div className="workflow-step"><div className="step-num">04</div><div className="step-body"><h4>Output & System Integration</h4><p>Results pushed to your existing systems — CRM, ERP, email, Slack, databases — with complete audit trail logging.</p></div></div>
            <div className="workflow-step"><div className="step-num">05</div><div className="step-body"><h4>Monitoring & Self-Improvement</h4><p>Continuous performance tracking. AI models retrain on new data. Weekly performance reports delivered automatically.</p></div></div>
          </div>
        </div>
        <div>
          <div className="workflow-visual">
            <div style={{"textAlign": "center"}}><span className="wf-label">DATA SOURCES</span></div>
            <div className="wf-row"><div className="wf-node"><i className="fas fa-database"></i> CRM</div><div className="wf-node"><i className="fas fa-file-alt"></i> Documents</div><div className="wf-node"><i className="fab fa-shopify"></i> Shopify</div></div>
            <div className="wf-arrow"><i className="fas fa-arrow-down"></i></div>
            <div style={{"textAlign": "center"}}><span className="wf-label">AI PROCESSING LAYER</span></div>
            <div className="wf-row"><div className="wf-node" style={{"borderColor": "rgba(6,182,212,.4)"}}><i className="fas fa-brain"></i> LLM Engine</div><div className="wf-node" style={{"borderColor": "rgba(6,182,212,.4)"}}><i className="fas fa-vector-square"></i> Vector DB</div></div>
            <div className="wf-arrow"><i className="fas fa-arrow-down"></i></div>
            <div style={{"textAlign": "center"}}><span className="wf-label">AUTOMATION ENGINE (n8n)</span></div>
            <div className="wf-row"><div className="wf-node" style={{"borderColor": "rgba(249,115,22,.4)"}}><i className="fas fa-cogs"></i> Rules Engine</div><div className="wf-node" style={{"borderColor": "rgba(249,115,22,.4)"}}><i className="fas fa-shield-alt"></i> Validation</div></div>
            <div className="wf-arrow"><i className="fas fa-arrow-down"></i></div>
            <div style={{"textAlign": "center"}}><span className="wf-label">OUTPUT CHANNELS</span></div>
            <div className="wf-row"><div className="wf-node"><i className="fab fa-slack"></i> Slack</div><div className="wf-node"><i className="fas fa-envelope"></i> Email</div><div className="wf-node"><i className="fas fa-database"></i> Database</div></div>
            <div className="wf-arrow"><i className="fas fa-arrow-down"></i></div>
            <div style={{"textAlign": "center"}}><span className="wf-label">MONITORING & ALERTS</span></div>
            <div className="wf-row"><div className="wf-node" style={{"borderColor": "rgba(16,185,129,.4)"}}><i className="fas fa-chart-bar"></i> Dashboard</div><div className="wf-node" style={{"borderColor": "rgba(16,185,129,.4)"}}><i className="fas fa-bell"></i> Real-time Alerts</div></div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {/*  ═══ ARCHITECTURE ═══  */}
  <section className="arch-section" id="architecture">
    <div className="container">
      <div className="section-head-center">
        <div className="section-eyebrow eyebrow-blue"><i className="fas fa-sitemap"></i> Technical Architecture</div>
        <h2 className="section-title">Enterprise-Grade <span className="gradient-text-blue">AI Infrastructure</span></h2>
        <p className="section-subtitle">Scalable, secure, and cloud-native. Built to handle millions of operations with 99.9% uptime and full audit trails.</p>
      </div>
      <div className="arch-diagram">
        <div className="arch-layer-label">CLIENT LAYER</div>
        <div className="arch-layer"><div className="arch-node" style={{"color": "#60A5FA"}}><i className="fas fa-globe"></i><span>Web App</span></div><div className="arch-node" style={{"color": "#60A5FA"}}><i className="fas fa-mobile-alt"></i><span>Mobile</span></div><div className="arch-node" style={{"color": "#60A5FA"}}><i className="fab fa-whatsapp"></i><span>WhatsApp</span></div><div className="arch-node" style={{"color": "#60A5FA"}}><i className="fab fa-slack"></i><span>Slack</span></div><div className="arch-node" style={{"color": "#60A5FA"}}><i className="fas fa-plug"></i><span>REST API</span></div></div>
        <div className="arch-connector"><i className="fas fa-chevron-down"></i></div>
        <div className="arch-layer-label">SECURITY & GATEWAY</div>
        <div className="arch-layer"><div className="arch-node" style={{"color": "#F97316"}}><i className="fab fa-cloudflare"></i><span>Cloudflare</span></div><div className="arch-node" style={{"color": "#F97316"}}><i className="fas fa-shield-alt"></i><span>Auth / JWT</span></div><div className="arch-node" style={{"color": "#F97316"}}><i className="fas fa-tachometer-alt"></i><span>Rate Limiter</span></div></div>
        <div className="arch-connector"><i className="fas fa-chevron-down"></i></div>
        <div className="arch-layer-label">AI PROCESSING CORE</div>
        <div className="arch-layer"><div className="arch-node" style={{"color": "#06B6D4"}}><i className="fas fa-brain"></i><span>LLM Router</span></div><div className="arch-node" style={{"color": "#06B6D4"}}><i className="fas fa-search"></i><span>Vector Search</span></div><div className="arch-node" style={{"color": "#06B6D4"}}><i className="fas fa-cogs"></i><span>n8n Engine</span></div><div className="arch-node" style={{"color": "#06B6D4"}}><i className="fas fa-memory"></i><span>Redis Cache</span></div></div>
        <div className="arch-connector"><i className="fas fa-chevron-down"></i></div>
        <div className="arch-layer-label">DATA & STORAGE</div>
        <div className="arch-layer"><div className="arch-node" style={{"color": "#10B981"}}><i className="fas fa-database"></i><span>PostgreSQL</span></div><div className="arch-node" style={{"color": "#10B981"}}><i className="fas fa-cube"></i><span>MongoDB</span></div><div className="arch-node" style={{"color": "#10B981"}}><i className="fas fa-microchip"></i><span>Pinecone</span></div><div className="arch-node" style={{"color": "#10B981"}}><i className="fab fa-aws"></i><span>S3 Storage</span></div></div>
        <div className="arch-connector"><i className="fas fa-chevron-down"></i></div>
        <div className="arch-layer-label">MONITORING & OBSERVABILITY</div>
        <div className="arch-layer"><div className="arch-node" style={{"color": "#A78BFA"}}><i className="fas fa-chart-area"></i><span>Grafana</span></div><div className="arch-node" style={{"color": "#A78BFA"}}><i className="fas fa-bug"></i><span>Sentry</span></div><div className="arch-node" style={{"color": "#A78BFA"}}><i className="fas fa-bell"></i><span>PagerDuty</span></div><div className="arch-node" style={{"color": "#A78BFA"}}><i className="fas fa-scroll"></i><span>Audit Logs</span></div></div>
      </div>
    </div>
  </section>

  {/*  ═══ PRICING ═══  */}
  <section className="pricing-section" id="pricing">
    <div className="container">
      <div className="section-head-center">
        <div className="section-eyebrow eyebrow-orange"><i className="fas fa-tags"></i> Transparent Pricing</div>
        <h2 className="section-title">One AI Tool or <span className="gradient-text-orange">The Whole Suite</span></h2>
        <p className="section-subtitle">Fixed-scope projects with no hidden costs. Scale from a single AI tool to a full intelligent business platform.</p>
      </div>
      <div className="pricing-grid gsap-stagger">
        <div className="pricing-card"><div className="pricing-plan">Starter</div><div className="pricing-price"><sup>$</sup>499<sub>/mo</sub></div><p className="pricing-desc">Perfect for small businesses deploying their first AI tool with essential features and integrations.</p><ul className="pricing-features"><li><i className="fas fa-check"></i> 1 AI Tool of your choice</li><li><i className="fas fa-check"></i> Up to 5,000 AI interactions/mo</li><li><i className="fas fa-check"></i> 2 integration connections</li><li><i className="fas fa-check"></i> Email support (48h response)</li><li><i className="fas fa-check"></i> Monthly performance report</li><li><i className="fas fa-check"></i> Basic monitoring dashboard</li><li className="disabled"><i className="fas fa-times"></i> Custom training data</li><li className="disabled"><i className="fas fa-times"></i> White-label option</li></ul><Link  to="/contact" className="pricing-cta secondary">Get Started</Link></div>
        <div className="pricing-card featured"><div className="pricing-plan">Growth</div><div className="pricing-price"><sup>$</sup>1,499<sub>/mo</sub></div><p className="pricing-desc">Full-stack AI platform for growing businesses ready to automate multiple operations at once.</p><ul className="pricing-features"><li><i className="fas fa-check"></i> 3 AI Tools bundled</li><li><i className="fas fa-check"></i> Up to 50,000 AI interactions/mo</li><li><i className="fas fa-check"></i> Unlimited integrations</li><li><i className="fas fa-check"></i> Priority support (12h response)</li><li><i className="fas fa-check"></i> Weekly performance reports</li><li><i className="fas fa-check"></i> Advanced analytics dashboard</li><li><i className="fas fa-check"></i> Custom training on your data</li><li className="disabled"><i className="fas fa-times"></i> White-label option</li></ul><Link  to="/contact" className="pricing-cta primary">Start Now — Most Popular</Link></div>
        <div className="pricing-card"><div className="pricing-plan">Enterprise</div><div className="pricing-price" style={{"fontSize": "2rem", "paddingTop": "8px"}}>Custom</div><p className="pricing-desc">Bespoke AI platform for enterprises needing unlimited scale, white-labeling, and dedicated SLA support.</p><ul className="pricing-features"><li><i className="fas fa-check"></i> All 9 AI Tools included</li><li><i className="fas fa-check"></i> Unlimited AI interactions</li><li><i className="fas fa-check"></i> Unlimited custom APIs & integrations</li><li><i className="fas fa-check"></i> Dedicated account manager</li><li><i className="fas fa-check"></i> 24/7 monitoring with SLA guarantee</li><li><i className="fas fa-check"></i> Full white-label & custom branding</li><li><i className="fas fa-check"></i> On-premise deployment option</li><li><i className="fas fa-check"></i> Quarterly AI strategy review</li></ul><Link  to="/contact" className="pricing-cta secondary">Request Custom Quote</Link></div>
      </div>
      <div style={{"textAlign": "center", "marginTop": "28px", "fontSize": ".88rem", "color": "#94A3B8"}}><i className="fas fa-info-circle" style={{"color": "#06B6D4"}}></i> All plans include a 14-day free pilot. No credit card required. Dedicated onboarding call included.</div>
    </div>
  </section>

  {/*  ═══ USE CASES ═══  */}
  <section className="usecases-section" id="use-cases">
    <div className="container">
      <div className="section-head-center" style={{"marginBottom": "40px"}}>
        <div className="section-eyebrow eyebrow-green"><i className="fas fa-industry"></i> Industry Use Cases</div>
        <h2 className="section-title">AI Solutions by <span className="gradient-text-cyan">Industry</span></h2>
        <p className="section-subtitle">Every industry has unique automation opportunities. See exactly how our AI tools deliver ROI in your sector.</p>
      </div>
      <div className="industry-tabs" id="industry-tabs">
        <button className="industry-tab active" data-industry="ecommerce">🛒 E-Commerce</button>
        <button className="industry-tab" data-industry="healthcare">🏥 Healthcare</button>
        <button className="industry-tab" data-industry="finance">💰 Finance</button>
        <button className="industry-tab" data-industry="restaurant">🍽️ Restaurants</button>
        <button className="industry-tab" data-industry="saas">⚙️ SaaS</button>
        <button className="industry-tab" data-industry="realestate">🏠 Real Estate</button>
      </div>
      <div className="usecase-panels active" id="usecase-ecommerce"><div className="usecase-card"><div className="usecase-icon">🤖</div><h4>AI Customer Support</h4><p>Auto-resolve order queries, returns, and shipping questions 24/7. Integrates with Shopify and WooCommerce in real-time.</p><span className="usecase-roi">ROI: -65% support costs</span></div><div className="usecase-card"><div className="usecase-icon">📦</div><h4>Smart Inventory AI</h4><p>Predict stock needs, auto-reorder, prevent stockouts during peak seasons. Trained on your 2+ years of sales history.</p><span className="usecase-roi">ROI: -35% holding costs</span></div><div className="usecase-card"><div className="usecase-icon">✉️</div><h4>AI Email Marketing</h4><p>Personalized cart abandonment, post-purchase, and win-back sequences with AI-generated subject lines.</p><span className="usecase-roi">ROI: +62% open rates</span></div><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Sales Forecasting</h4><p>Predict next month's GMV with 94% accuracy. Plan inventory, staffing, and marketing spend proactively.</p><span className="usecase-roi">ROI: +28% profit margin</span></div><div className="usecase-card"><div className="usecase-icon">✍️</div><h4>Product Description AI</h4><p>Generate SEO-optimized descriptions for thousands of SKUs simultaneously. 50+ templates across categories.</p><span className="usecase-roi">ROI: -85% writing time</span></div><div className="usecase-card"><div className="usecase-icon">🎯</div><h4>Customer Segmentation</h4><p>AI-powered RFM analysis and behavioral clustering. Dynamic segments that update in real-time for maximum relevance.</p><span className="usecase-roi">ROI: +40% LTV</span></div></div>
      <div className="usecase-panels" id="usecase-healthcare"><div className="usecase-card"><div className="usecase-icon">📋</div><h4>Medical Document AI</h4><p>Extract patient info, diagnoses, and prescriptions from clinical notes, discharge summaries, and lab reports with 99% accuracy.</p><span className="usecase-roi">ROI: -90% admin time</span></div><div className="usecase-card"><div className="usecase-icon">📅</div><h4>Appointment AI Bot</h4><p>Automated scheduling, reminders, and rescheduling via WhatsApp and SMS. Reduces no-shows by 60%.</p><span className="usecase-roi">ROI: -60% no-shows</span></div><div className="usecase-card"><div className="usecase-icon">🧠</div><h4>Clinical Knowledge Base</h4><p>AI-powered medical knowledge base for staff. Instant protocol lookups, drug interactions, and compliance guidance.</p><span className="usecase-roi">ROI: -70% lookup time</span></div><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Patient Analytics</h4><p>Predict readmission risk, identify high-risk patients, and optimize bed allocation with ML forecasting models.</p><span className="usecase-roi">ROI: -25% readmissions</span></div><div className="usecase-card"><div className="usecase-icon">🤖</div><h4>Patient Support Bot</h4><p>Answer symptom questions, medication queries, and post-discharge instructions. Escalates to nurses automatically.</p><span className="usecase-roi">ROI: +45% satisfaction</span></div><div className="usecase-card"><div className="usecase-icon">📄</div><h4>Insurance Claims AI</h4><p>Auto-process insurance claims, verify coverage, and submit to payers. Reduces processing time from days to minutes.</p><span className="usecase-roi">ROI: -80% claim time</span></div></div>
      <div className="usecase-panels" id="usecase-finance"><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Risk Analytics AI</h4><p>Real-time credit risk scoring, fraud detection, and portfolio analysis using 50+ financial signals per transaction.</p><span className="usecase-roi">ROI: -40% fraud losses</span></div><div className="usecase-card"><div className="usecase-icon">📄</div><h4>Document Intelligence</h4><p>KYC document verification, loan application processing, and contract analysis — automated and fully compliant.</p><span className="usecase-roi">ROI: -75% processing time</span></div><div className="usecase-card"><div className="usecase-icon">🤖</div><h4>Financial Advisor Bot</h4><p>AI chatbot trained on your financial products. Answers customer queries, cross-sells, and qualifies leads 24/7.</p><span className="usecase-roi">ROI: +35% lead conversion</span></div><div className="usecase-card"><div className="usecase-icon">📈</div><h4>Revenue Forecasting</h4><p>AUM forecasting, churn prediction for premium clients, and seasonal pattern analysis for resource planning.</p><span className="usecase-roi">ROI: +22% retention</span></div><div className="usecase-card"><div className="usecase-icon">✉️</div><h4>Client Communication AI</h4><p>Personalized market updates, portfolio reports, and regulatory disclosures — auto-generated and compliant.</p><span className="usecase-roi">ROI: -60% report time</span></div><div className="usecase-card"><div className="usecase-icon">🔍</div><h4>Compliance Monitoring</h4><p>AI scans all communications and transactions for compliance violations with real-time alerting and case management.</p><span className="usecase-roi">ROI: -90% audit time</span></div></div>
      <div className="usecase-panels" id="usecase-restaurant"><div className="usecase-card"><div className="usecase-icon">🤖</div><h4>AI Reservation Bot</h4><p>WhatsApp and web AI takes bookings, confirms tables, manages waitlists, and sends automated reminders round the clock.</p><span className="usecase-roi">ROI: -50% no-shows</span></div><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Demand Forecasting</h4><p>Predict covers for each service. Optimize staffing, food prep, and inventory ordering. Reduce food waste by 30%.</p><span className="usecase-roi">ROI: -30% food waste</span></div><div className="usecase-card"><div className="usecase-icon">✉️</div><h4>Guest Retention AI</h4><p>Automated loyalty campaigns, birthday offers, and win-back sequences based on visit history and preferences.</p><span className="usecase-roi">ROI: +45% repeat visits</span></div><div className="usecase-card"><div className="usecase-icon">📋</div><h4>Menu Optimization AI</h4><p>Analyze dish performance, identify slow movers, and generate data-driven menu recommendations for maximum GP.</p><span className="usecase-roi">ROI: +18% gross profit</span></div><div className="usecase-card"><div className="usecase-icon">⭐</div><h4>Review Response AI</h4><p>Auto-respond to Google, Zomato, and TripAdvisor reviews in your brand voice. Escalate negative reviews instantly.</p><span className="usecase-roi">ROI: +0.4★ avg rating</span></div><div className="usecase-card"><div className="usecase-icon">📣</div><h4>Social Content AI</h4><p>Daily food photos, stories, and captions generated from your menu items. Posted on schedule to all platforms.</p><span className="usecase-roi">ROI: +200% social reach</span></div></div>
      <div className="usecase-panels" id="usecase-saas"><div className="usecase-card"><div className="usecase-icon">🎯</div><h4>Lead Scoring AI</h4><p>Score every signup based on company data, behavior, and 50+ fit signals. Route hot leads to sales instantly.</p><span className="usecase-roi">ROI: 3x more SQLs</span></div><div className="usecase-card"><div className="usecase-icon">⚠️</div><h4>Churn Prediction</h4><p>Identify at-risk accounts 3 weeks before they churn. Trigger automated save campaigns and CSM alerts automatically.</p><span className="usecase-roi">ROI: -40% churn rate</span></div><div className="usecase-card"><div className="usecase-icon">🧠</div><h4>In-App AI Assistant</h4><p>Help center AI trained on your docs. Answers user questions, guides onboarding, and reduces support tickets by 65%.</p><span className="usecase-roi">ROI: -65% tickets</span></div><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Usage Analytics AI</h4><p>Identify power users, detect feature adoption gaps, and auto-surface expansion opportunities for your sales team.</p><span className="usecase-roi">ROI: +35% NRR</span></div><div className="usecase-card"><div className="usecase-icon">✉️</div><h4>Lifecycle Email AI</h4><p>Behavioral trigger sequences for activation, expansion, and renewal — personalized for each account's usage pattern.</p><span className="usecase-roi">ROI: +28% activation</span></div><div className="usecase-card"><div className="usecase-icon">📄</div><h4>Proposal Generator AI</h4><p>Auto-generate custom proposals, case studies, and pitch decks from your CRM data in under 60 seconds.</p><span className="usecase-roi">ROI: -80% proposal time</span></div></div>
      <div className="usecase-panels" id="usecase-realestate"><div className="usecase-card"><div className="usecase-icon">🤖</div><h4>Property AI Chatbot</h4><p>Answer buyer queries, schedule viewings, and qualify leads 24/7 via your website and WhatsApp automatically.</p><span className="usecase-roi">ROI: +60% qualified leads</span></div><div className="usecase-card"><div className="usecase-icon">📊</div><h4>Property Valuation AI</h4><p>Instant AI valuations based on location, comparables, market trends, and property attributes with 97% accuracy.</p><span className="usecase-roi">ROI: +35% valuation speed</span></div><div className="usecase-card"><div className="usecase-icon">✉️</div><h4>Listing Copywriting AI</h4><p>Generate compelling property descriptions and social posts from photos and spec sheets in seconds.</p><span className="usecase-roi">ROI: +25% inquiry rate</span></div><div className="usecase-card"><div className="usecase-icon">🎯</div><h4>Buyer Matching AI</h4><p>Match new listings to buyers in your database based on stated preferences and search behavior history.</p><span className="usecase-roi">ROI: -50% time-to-sale</span></div><div className="usecase-card"><div className="usecase-icon">📋</div><h4>Document Processing</h4><p>Auto-extract data from sale agreements, KYC docs, and title deeds. Reduce compliance overhead significantly.</p><span className="usecase-roi">ROI: -80% admin time</span></div><div className="usecase-card"><div className="usecase-icon">📈</div><h4>Market Intelligence AI</h4><p>Track local property trends, competitor listings, and demand signals. Generate weekly market reports automatically.</p><span className="usecase-roi">ROI: Better deal timing</span></div></div>
    </div>
  </section>

  {/*  ═══ SCREENSHOTS ═══  */}
  <section className="screenshots-section" id="screenshots">
    <div className="container">
      <div className="section-head-center">
        <div className="section-eyebrow eyebrow-blue"><i className="fas fa-images"></i> Screenshots</div>
        <h2 className="section-title">See Our AI Tools <span className="gradient-text-blue">In Action</span></h2>
        <p className="section-subtitle">Every interface is designed for clarity and ease of use — powerful AI behind a beautiful, intuitive front-end.</p>
      </div>
      <div className="screenshots-grid gsap-stagger">
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#06B6D4", "top": "20%", "left": "20%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#06B6D4", "marginBottom": "8px", "fontWeight": "700"}}>AI CHATBOT DASHBOARD</div><div className="mockup-line w80"></div><div className="mockup-line w60"></div><div style={{"display": "grid", "gridTemplateColumns": "1fr 1fr", "gap": "5px", "marginTop": "8px"}}><div style={{"background": "rgba(6,182,212,.1)", "borderRadius": "5px", "padding": "7px", "textAlign": "center"}}><div style={{"fontSize": ".68rem", "color": "#06B6D4", "fontWeight": "700"}}>80%</div><div style={{"fontSize": ".55rem", "color": "#94A3B8"}}>Resolution</div></div><div style={{"background": "rgba(16,185,129,.1)", "borderRadius": "5px", "padding": "7px", "textAlign": "center"}}><div style={{"fontSize": ".68rem", "color": "#10B981", "fontWeight": "700"}}>4.8★</div><div style={{"fontSize": ".55rem", "color": "#94A3B8"}}>CSAT</div></div></div></div></div><div className="screenshot-info"><h4>AI Support Agent Dashboard</h4><p>Real-time conversation monitoring and analytics</p></div></div>
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#2563EB", "top": "30%", "right": "20%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#60A5FA", "marginBottom": "8px", "fontWeight": "700"}}>DOCUMENT PROCESSING AI</div><div style={{"border": "1px dashed rgba(37,99,235,.3)", "borderRadius": "5px", "padding": "8px", "textAlign": "center", "marginBottom": "7px"}}><div style={{"fontSize": ".58rem", "color": "#94A3B8"}}>📄 invoice_Q3.pdf → Processing...</div></div><div className="mockup-line w80"></div><div style={{"background": "rgba(16,185,129,.1)", "borderRadius": "5px", "padding": "5px", "marginTop": "5px", "fontSize": ".58rem", "color": "#10B981"}}>✓ 14 fields extracted | 99.2% confidence</div></div></div><div className="screenshot-info"><h4>Document Intelligence UI</h4><p>Instant extraction with confidence scoring</p></div></div>
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#F97316", "top": "10%", "left": "30%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#F97316", "marginBottom": "8px", "fontWeight": "700"}}>SALES AI PIPELINE</div><div style={{"display": "flex", "flexDirection": "column", "gap": "4px"}}><div style={{"background": "rgba(249,115,22,.1)", "borderRadius": "5px", "padding": "5px", "display": "flex", "justifyContent": "space-between"}}><span style={{"fontSize": ".58rem", "color": "white"}}>Acme Corp</span><span style={{"fontSize": ".58rem", "color": "#10B981", "fontWeight": "700"}}>94%</span></div><div style={{"background": "rgba(249,115,22,.08)", "borderRadius": "5px", "padding": "5px", "display": "flex", "justifyContent": "space-between"}}><span style={{"fontSize": ".58rem", "color": "white"}}>TechFlow Inc</span><span style={{"fontSize": ".58rem", "color": "#06B6D4", "fontWeight": "700"}}>87%</span></div><div style={{"background": "rgba(249,115,22,.05)", "borderRadius": "5px", "padding": "5px", "display": "flex", "justifyContent": "space-between"}}><span style={{"fontSize": ".58rem", "color": "white"}}>DataSoft Ltd</span><span style={{"fontSize": ".58rem", "color": "#60A5FA", "fontWeight": "700"}}>79%</span></div></div></div></div><div className="screenshot-info"><h4>Sales AI Lead Scoring</h4><p>AI-ranked prospects with fit scores</p></div></div>
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#10B981", "top": "40%", "left": "10%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#10B981", "marginBottom": "8px", "fontWeight": "700"}}>ANALYTICS AI FORECAST</div><div style={{"height": "45px", "background": "rgba(16,185,129,.05)", "borderRadius": "5px", "overflow": "hidden", "marginBottom": "7px"}}><svg viewBox="0 0 120 45" style={{"width": "100%", "height": "100%"}}><polyline points="0,42 20,35 40,27 60,18 80,12 100,6 120,2" fill="none" stroke="#10B981" stroke-width="2"/></svg></div><div style={{"fontSize": ".62rem", "color": "#10B981"}}>↑ Revenue: +$128K next month forecast</div></div></div><div className="screenshot-info"><h4>Predictive Analytics Dashboard</h4><p>30-day revenue forecast with trend visualization</p></div></div>
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#8B5CF6", "top": "20%", "right": "10%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#A78BFA", "marginBottom": "8px", "fontWeight": "700"}}>CONTENT AI GENERATOR</div><div style={{"background": "rgba(139,92,246,.1)", "borderRadius": "5px", "padding": "7px", "fontSize": ".58rem", "color": "#94A3B8", "lineHeight": "1.6"}}>"10 Ways to Automate Operations with AI..." <span style={{"color": "#A78BFA"}}>✓ SEO · 1,200 words</span></div><div className="mockup-line w60" style={{"marginTop": "7px"}}></div><div className="mockup-line w40"></div></div></div><div className="screenshot-info"><h4>Content Generation Engine</h4><p>Brand-voice AI with SEO optimization built-in</p></div></div>
        <div className="screenshot-card"><div className="screenshot-mockup"><div className="mockup-glow" style={{"background": "#F472B6", "top": "30%", "left": "40%"}}></div><div className="mockup-ui"><div className="mockup-header"><div className="mockup-dot" style={{"background": "#EF4444"}}></div><div className="mockup-dot" style={{"background": "#F59E0B"}}></div><div className="mockup-dot" style={{"background": "#10B981"}}></div></div><div style={{"fontSize": ".62rem", "color": "#F472B6", "marginBottom": "8px", "fontWeight": "700"}}>WORKFLOW AUTOMATION</div><div style={{"display": "flex", "alignItems": "center", "gap": "5px", "overflow": "hidden", "padding": "4px 0"}}><div style={{"background": "rgba(37,99,235,.15)", "borderRadius": "5px", "padding": "4px 7px", "fontSize": ".55rem", "color": "#60A5FA", "whiteSpace": "nowrap"}}>Trigger</div><span style={{"color": "rgba(255,255,255,.3)", "fontSize": ".7rem"}}>→</span><div style={{"background": "rgba(6,182,212,.15)", "borderRadius": "5px", "padding": "4px 7px", "fontSize": ".55rem", "color": "#06B6D4", "whiteSpace": "nowrap"}}>AI Process</div><span style={{"color": "rgba(255,255,255,.3)", "fontSize": ".7rem"}}>→</span><div style={{"background": "rgba(16,185,129,.15)", "borderRadius": "5px", "padding": "4px 7px", "fontSize": ".55rem", "color": "#10B981", "whiteSpace": "nowrap"}}>Output</div></div><div style={{"fontSize": ".58rem", "color": "#10B981", "marginTop": "7px"}}>✓ 1,247 executions today · 0 errors</div></div></div><div className="screenshot-info"><h4>n8n Workflow Builder</h4><p>Visual automation builder with live monitoring</p></div></div>
      </div>
    </div>
  </section>

  {/*  ═══ CTA ═══  */}
  <section className="ai-cta-section">
    <div className="container">
      <div className="ai-cta-card">
        <div className="section-eyebrow eyebrow-orange" style={{"justifyContent": "center", "marginBottom": "16px", "display": "inline-flex"}}><i className="fas fa-rocket"></i> Ready to Deploy?</div>
        <h2>Launch Your First AI Tool <span className="gradient-text-orange">This Week</span></h2>
        <p>Book a free 30-minute AI strategy call. We'll map your biggest automation opportunity, show you a live demo, and give you a no-obligation proposal with exact ROI estimates.</p>
        <div className="ai-cta-btns">
          <Link  to="/contact" className="cta-btn primary"><i className="fas fa-calendar-alt"></i> Book Free Strategy Call</Link>
          <a href="https://wa.me/917877813270?text=Hi!+I'm+interested+in+APITIDE's+AI+Tools" target="_blank" rel="noopener" className="cta-btn secondary" style={{"background": "rgba(37,211,102,.1)", "borderColor": "rgba(37,211,102,.3)", "color": "#25D366"}}><i className="fab fa-whatsapp"></i> WhatsApp Us</a>
          <Link  to="/projects" className="cta-btn secondary">View Case Studies <i className="fas fa-arrow-right"></i></Link>
        </div>
      </div>
    </div>
  </section>

  {/*  FOOTER  */}
    </main>
  );
}
